### ISSUE TITLE
Timeout in fetching download link, not handled properly

### ISSUE THREAD

**Issue by Wheest** [ghwns9652/Minecraft-Bedrock-Server-Updater#2]
Hey, thanks for the repo.

In the `mcserver_autoupdater.py` try-except block [around line 22](https://github.com/ghwns9652/Minecraft-Bedrock-Server-Updater/blob/9f07242623265d500a8e359eeff9b3cd31ddb266/updater/mcserver_autoupdater.py#L22), if there is a timeout check and a log if a timeout occurs `logging.error("timeout raised, recovering")`.  

However, if the timeout occurs, there is no recovery, instead the program crashes because it tries to run the next line `soup = BeautifulSoup(page.content, "html.parser")`, and we do not have a `page` variable set.

For me, this keeps happening because `https://www.minecraft.net/en-us/download/server/bedrock` is timing out (other sites such as `google.com` do not, and return the page correctly.  This is because I'm using AWS, and I'm pretty sure that my IP range is blocked by Minecraft.net to discourage scraping.  I can access the site using b4s locally.

**Comment by ghwns9652** [comment]
Thanks for reporting issue. I just addeed `current_download_link.txt` to my repo for backup download link.
`mcserver_autoupdater.py` now use this backup link when original url's timeout is raised.
So, `mcserver_autoupdater.py` will work on AWS.

I'll try to check new version of bedrock server every day and update `current_download_link.txt` using script
